# Generated by Django 4.2.5 on 2023-09-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_ec2_SecurityGroup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitygroup',
            name='group_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='securitygroup',
            name='group_name',
            field=models.CharField(max_length=100),
        ),
    ]
