# Generated by Django 4.2.5 on 2023-09-17 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aws_ec2_SecurityGroup', '0002_alter_securitygroup_group_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SecurityGroup',
        ),
    ]
